<Project Sdk="MSTest.Sdk/4.0.1">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>..\..\SujaySarma.Data.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Builders\SqlQueryBuilderJoinTests.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\SujaySarma.Data.Core\SujaySarma.Data.Core.csproj" />
		<ProjectReference Include="..\..\SujaySarma.Data.SqlServer\SujaySarma.Data.SqlServer.csproj" />
	</ItemGroup>

</Project>
