<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>SS - Favicon.ico</ApplicationIcon>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>D:\Sujay\src\SujaySarma.Data\SujaySarma.Data.snk</AssemblyOriginatorKeyFile>
		<Title>Sujay Sarma's Core assembly for data access</Title>
		<Authors>Sujay V. Sarma</Authors>
		<Description>This library is used as a dependency by other libraries named with the prefix `SujaySarma.Data.*`. `SujaySarma.Data.Core` provides core reflection attributes, attribute discovery, validation, data conversion, population, hydration and evaporation services to the upstream consuming libraries.</Description>
		<Copyright>Copyright (c) 2025 and beyond Sujay V Sarma. All Rights Reserved.</Copyright>
		<PackageProjectUrl>https://github.com/sujayvsarma/SujaySarma.Data</PackageProjectUrl>
		<PackageIcon>SS Logo.png</PackageIcon>
		<RepositoryUrl>https://github.com/sujayvsarma/SujaySarma.Data</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>data access,core,library,sql server,windows,registry,json,sql,sqlserver,azure,tables,databases,files,flat file,csv,txt</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<AssemblyVersion>10.0.0.0</AssemblyVersion>
		<FileVersion>10.0.0.0</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<PackageOutputPath>$(SolutionDir)Redist\</PackageOutputPath>
		<IncludeSymbols>False</IncludeSymbols>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>[10.0.0.0] - Complete rewrite of the library! This version is NOT backwards compatible with previous versions.</PackageReleaseNotes>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="README.md" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="README.md">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</Content>
		<Content Include="SS - Favicon.ico" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\SS Logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SujaySarma.Data.Files.TokenLimitedFiles.Tests" Key="002400000480000094000000060200000024000052534131000400000100010049e1a16666e0edbb632072ce659d6ae255de0a1efa763d859f86af7f93e4f41a43b6401651398ef925d23da79ea5ad5e950a6731bd79cddb8135ce47be023279c66febd15ab209f200ea8fa146f6c8b64307edeb65b0c467ef8b781f5f05da714c0230b9f190a3156f2150b10700af8f598b52edeccbc43f459dd343ae5e59df" />
	</ItemGroup>

</Project>
