using System;

namespace SujaySarma.Data.Core.Attributes;

/// <summary>
/// An interface implemented by <see cref="Attribute"/>s on member properties/fields of business entity 
/// classes/structs/fields to indicate they are populated by the backend datastorage systems on persistence. Such 
/// fields are not included in the persistence (inserts/updates) instructions generated by the ORM library system.
/// </summary>
public interface IBackendSystemPopulatedField : ISystemPopulatedField
{
}
