using System;

namespace SujaySarma.Data.Core.Attributes;

/// <summary>
/// An interface implemented by <see cref="Attribute"/>s on member properties/fields of business entity 
/// classes/structs/fields to indicate they must be populated by this ORM library system on persistence. Such 
/// fields are included in the persistence (inserts/updates) instructions generated by the ORM library system.
/// </summary>
public interface IOrmPopulatedField : ISystemPopulatedField
{

    /// <summary>
    /// Returns the appropriate value as per the provided options.
    /// </summary>
    /// <param name="currentValue">The current value of the member property or field.</param>
    /// <returns>Value.</returns>
    public object? GetOrmPopulatedValue(object? currentValue);
}