<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>SS - Favicon.ico</ApplicationIcon>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>D:\Sujay\OneDrive - Sujay Sarma\Documents\Keys\SujaySarma.Data.snk</AssemblyOriginatorKeyFile>
		<Title>Sujay Sarma's Token-limited files Parser/Writer SDK</Title>
		<Authors>Sujay V. Sarma</Authors>
		<Description>This library provides mechanisms to read from and write data to token delimited files -- such as comma, semi-colon, space, tab, etc seperated flat text files. These files may have file extensions of .csv or .txt. In addition to disk files, the library also supports reading from and writing to streams (eg: Http file download streams, Uploaded files from web-based forms, etc). This library is highly performance optimised. My benchmark: Parse and correctly load a flat text file with 20,000 records in less than 1 second. This file contains a mix of good data, erroroneous data, quoted, unquoted, badly quoted, wrongly quoted, etc. that interprets the RFC specification in both letter and spirit. Typically, this library surpasses this metric by finishing in less than 300ms.</Description>
		<Copyright>Copyright (c) 2025 and beyond Sujay V Sarma. All Rights Reserved.</Copyright>
		<PackageProjectUrl>https://github.com/sujayvsarma/SujaySarma.Data</PackageProjectUrl>
		<PackageIcon>SS Logo.png</PackageIcon>
		<RepositoryUrl>https://github.com/sujayvsarma/SujaySarma.Data</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>data access,library,flatfiles,flat files,token-limited,token limited,comma,tab,semi-colon,semi colon,semicolon,json,databases</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<AssemblyVersion>10.0.1.0</AssemblyVersion>
		<FileVersion>10.0.1.0</FileVersion>
		<Version>$(AssemblyVersion)</Version>
		<PackageOutputPath>$(SolutionDir)Redist\</PackageOutputPath>
		<IncludeSymbols>False</IncludeSymbols>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>[10.0.1.0] - BUGFIX: Fixed an issue writing and parsing quoted values in some cases.</PackageReleaseNotes>
	</PropertyGroup>

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
		<DebugType>embedded</DebugType>
		<NoWarn>1701;1702;SYSLIB1045;IDE0028;IDE0034;IDE0063;IDE0066;IDE0075;IDE0090;IDE0130;IDE0290;IDE0300;IDE0301;IDE0305;IDE0306;IDE0330;IDE1005;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="README.md" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</Content>
		<Content Include="SS - Favicon.ico" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\SS Logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SujaySarma.Data.Core" Version="10.0.0" />
	</ItemGroup>

	<!--<ItemGroup>
	  <ProjectReference Include="..\SujaySarma.Data.Core\SujaySarma.Data.Core.csproj" />
	</ItemGroup>-->

	<ItemGroup>
		<InternalsVisibleTo Include="SujaySarma.Data.TokenLimitedFiles.Tests" Key="0024000004800000940000000602000000240000525341310004000001000100ed84115e5dbd602a8799adf57461c4a1f07967658d6be96694e5f4ce2b17afa59fe0a3c02160c427082d3d11f1a77d0feb156f44187947160523fef6e116879c2865a6340f8ce86a6d24918635df8b5e4a7eedb3a51e09fe164cdfb572235aa1451a60d0fe027425401f3f3d969e3f8336dfff7c0ed0797b7f699213d52bd6c3" />
	</ItemGroup>

</Project>
